name: macOS with Playit.gg RDP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust (if not present)
      run: |
        if ! command -v cargo >/dev/null; then
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        fi

    - name: Clone Playit Agent Repository
      run: |
        git clone https://github.com/playit-cloud/playit-agent.git

    - name: Build Playit Agent
      working-directory: playit-agent
      run: |
        cargo build --release

        # Verify the binary is created
        if [ ! -f "target/release/playit-cli" ]; then
          echo "Build failed: Playit Agent binary not found."
          exit 1
        fi

    - name: Run Playit agent with secret
      working-directory: playit-agent
      env:
        PLAYIT_SECRET: ${{ secrets.PL }}
      run: |
        ./target/release/playit-cli --secret "$PLAYIT_SECRET"
