name: macos hosting
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up environment
      env:
        ZROK_TOKEN: ${{ secrets.ZROK_TOKEN }}
        PASSWD: ${{ secrets.PASSWD }}
      run: |
        source setup.sh "$PASSWD" "$PASSWD" "$ZROK_TOKEN"
    - name: Keep session alive for debugging
      uses: mxschmitt/action-tmate@v2
