name: macOS Remote Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-remote-desktop:
    runs-on: [macOS-latest]
    timeout-minutes: 360  # Set the job to run for 6 hours

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Install Required Tools
        run: |
          brew install xrdb
          brew install socat

      - name: Install VNC Server
        run: |
          brew install tiger-vnc
          vncserver -localhost no

      - name: Print VNC Connection Info
        run: |
          echo "VNC Server is running. Use the following connection details:"
          echo "IP Address: $(curl -s ifconfig.me)"
          echo "Port: 5901 (default for VNC)"
          echo "Use Remote Desktop to connect to this IP address with the username 'runner' and the password 'github'."

      - name: Keep the Runner Active
        run: |
          # Keep the runner active by running a no-op command in a loop
          while true; do
            sleep 3600  # Sleep for 1 hour
          done
        shell: bash
