name: macOS with Playit.gg RDP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies for Building Playit Agent
      run: |
        echo "Updating and installing dependencies..."
        brew update
        brew install go git

    - name: Clone Playit Agent Repository
      run: |
        echo "Cloning the Playit Agent source code..."
        git clone https://github.com/playit-cloud/playit-agent.git
        cd playit-agent

    - name: Initialize Go Module
      working-directory: playit-agent
      run: |
        echo "Initializing Go module..."
        go mod init playit-agent
        go mod tidy

    - name: Build Playit Agent
      working-directory: playit-agent
      run: |
        echo "Building Playit Agent from source..."
        # Adjust the path to the Go files, if necessary
        go build -o playit-agent ./...

        # Verify the binary is created
        if [ ! -f "playit-agent" ]; then
          echo "Build failed: Playit Agent binary not found."
          exit 1
        fi

    - name: Run Playit Agent
      working-directory: playit-agent
      run: |
        echo "Starting Playit Agent..."
        ./playit-agent login

        echo "Playit Agent is running. Go to your Playit.gg account to connect the tunnel."
