name: macOS
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        curl -L https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64 \ 
          -o playit && chmod +x playit
        ./playit setup   # click claim link in logs
        nohup ./playit tunnel tcp --port $APP_PORT &
        sleep 5
        ./playit tunnel list

