name: macos hosting
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        env:
          ZROK_TOKEN: ${{ secrets.ZROK_TOKEN }}
          PASSWD: ${{ secrets.PASSWD }}
        run: |
          chmod +x setup.sh
          ./setup.sh "$PASSWD" "$PASSWD" "$ZROK_TOKEN"
      - name: Setup tmate Session
        uses: mxschmitt/action-tmate@v2
