name: macOS RDP via playit.gg

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  APP_PORT: 8080

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Clone playit-agent source
        run: |
          git clone https://github.com/playit-cloud/playit-agent.git   # get the agent source :contentReference[oaicite:2]{index=2}

      - name: Build playit-agent
        working-directory: playit-agent
        run: |
          brew install rust                                           # install Rust toolchain :contentReference[oaicite:3]{index=3}
          cargo build --release                                      # outputs binaries under target/release :contentReference[oaicite:4]{index=4}

      - name: Install playit binary
        run: |
          # the CLI binary is named "playit-cli", so rename it to "playit"
          mv playit-agent/target/release/playit-cli ./playit          # ← fixed name
          chmod +x ./playit

      - name: Enable VNC (Screen Sharing)
        run: |
          sudo systemsetup -setremotelogin on
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate \
            -configure -access -on \
            -privs -all \
            -restart -agent \
            -menu

      - name: Run setup.sh (root-located)
        run: |
          chmod +x ./setup.sh
          ./setup.sh "$VNC_PASS" "$VNC_PASS"

      - name: Authenticate playit.gg agent
        run: |
          nohup ./playit setup &
          sleep 10

      - name: Start playit.gg TCP tunnel
        run: |
          nohup ./playit tunnel tcp --port $APP_PORT &
          sleep 5
          ./playit tunnel list

      - name: Keep session alive
        run: sleep 3600
