name: macOS RDP via playit.gg

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  APP_PORT: 8080

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build playit-agent
        working-directory: playit-agent
        run: |
          brew install rust                    # install Rust toolchain :contentReference[oaicite:0]{index=0}
          cargo build --release                # produces target/release/playit :contentReference[oaicite:1]{index=1}

      - name: Install playit binary
        run: |
          mv playit-agent/target/release/playit ./playit
          chmod +x ./playit

      - name: Enable VNC (Screen Sharing)
        run: |
          sudo systemsetup -setremotelogin on
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate \
            -configure -access -on \
            -privs -all \
            -restart -agent \
            -menu                            # enable VNC :contentReference[oaicite:2]{index=2}

      - name: Run setup.sh
        run: |
          chmod +x .github/setup.sh
          .github/setup.sh "$VNC_PASS" "$VNC_PASS"

      - name: Authenticate playit.gg agent
        run: |
          nohup ./playit setup &
          sleep 10

      - name: Start playit.gg tunnel
        run: |
          nohup ./playit tunnel tcp --port $APP_PORT &
          sleep 5
          ./playit tunnel list

      - name: Keep alive
        run: sleep 3600
