name: macOS Setup

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Connect to PlayIt.gg
      env:
        PLAYIT_SECRET: ${{ secrets.PL }}
      run: |
        PLAYIT_IP=$(curl -s https://api.playit.gg/v1/tunnel -H "Authorization: Bearer $PLAYIT_SECRET" | jq -r '.ip')
        PLAYIT_PORT=$(curl -s https://api.playit.gg/v1/tunnel -H "Authorization: Bearer $PLAYIT_SECRET" | jq -r '.port')
        echo "IP: $PLAYIT_IP"
        echo "Port: $PLAYIT_PORT"
        # Use the IP and Port to connect via Remote Desktop
