name: macOS Remote Desktop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-remote-desktop:
    runs-on: [macOS-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Install xrdb
        run: |
          brew install xrdb
          sudo brew services start xrdb

      - name: Allow Remote Login
        run: |
          sudo systemsetup -setremotelogin on

      - name: Print IP Address
        run: |
          echo "IP Address: $(curl -s ifconfig.me)"
          echo "Use Remote Desktop to connect to this IP address with the username 'runner' and the password 'github'."
