name: macOS-VNC-Playit
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew update
          chmod +x setup.sh
          ./setup.sh
        env:
          PLAYIT_SECRET: ${{ secrets.PLAYIT_SECRET }}  # Your Playit.gg secret
