name: macOS
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Environment
      env:
        ZROK_TOKEN: ${{ secrets.ZROK_TOKEN }}
        VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
      run: |
        source setup.sh "$VNC_PASSWORD" "$ZROK_TOKEN"
    - name: Start zrok Tunnel
      run: |
        zrok share private --backend-mode tcpTunnel --headless --verbose tcp://localhost:5900
    - name: Keep alive for 6 hours
      run: sleep 21600 && sudo shutdown -h now
    - name: Setup tmate Session
      uses: mxschmitt/action-tmate@v2
