name: macos hosting
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting the Environment Up.
      env:
        ZROK_TOKEN: ${{ secrets.ZROK_TOKEN }}
        PASSWD: ${{ secrets.PASSWD }}
      run: source setup.sh "$PASSWD" "$PASSWD" "$ZROK_TOKEN"
    - name: Get zrok tunnel endpoint
      run: curl -s http://127.0.0.1:8080/api/tunnels | jq -r '.tunnels[0].public_url'
    - name: Setup tmate Session
      uses: mxschmitt/action-tmate@v2
