name: macOS Remote Desktop with Playit.gg

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-remote-desktop:
    runs-on: macOS-latest
    timeout-minutes: 360  # Set the job to run for 6 hours

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Install Playit.gg
        run: |
          brew install wget
          wget https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-macos.zip
          unzip playit-macos.zip
          chmod +x playit
          mv playit /usr/local/bin/

      - name: Start Playit.gg Tunnel
        run: |
          echo "${{ secrets.PLAYIT_SECRET }}" > playit-auth.key
          nohup ./playit -s playit-auth.key > playit.log 2>&1 &

      - name: Enable Remote Desktop
        run: |
          # Enable Remote Desktop
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on \
            -users runner -privs -all -restart -agent

          # Print connection details
          echo "Tunnel IP: international-latter.gl.at.ply.gg:43837"
          echo "Username: runner"
          echo "Password: github"

      - name: Keep the Runner Active
        run: |
          # Keep the runner active by running a no-op command in a loop
          while true; do
            sleep 3600  # Sleep for 1 hour
          done
        shell: bash
