name: macOS
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setting the Environment Up
      env:
        ZROK_TOKEN: ${{ secrets.ZROK_TOKEN }}  # Store your zrok token in GitHub Secrets
        PASSWD: ${{ secrets.PASSWD }}
      run: |
        source setup.sh "$PASSWD" "$PASSWD" "$ZROK_TOKEN"
    - name: zrok is now listening to VNC connections on...
      run: |
        zrok share private --backend-mode proxy --target localhost:5900 > /dev/null 2>&1
        echo "Public URL: $(zrok list | grep tcp | awk '{print $3}')"
    - name: Keep alive for 6 hours
      run: sleep 21600 && sudo shutdown -h now
    - name: Setup tmate Session
      uses: mxschmitt/action-tmate@v2
