# .github/workflows/action.yml
name: macOS
on: workflow_dispatch
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Environment
      env:
        PINGGY_TOKEN: ${{ secrets.PINGGY_TOKEN }}
      run: source setup.sh "$PINGGY_TOKEN"
    - name: Keep alive for 6 hours
      run: sleep 21600
    - name: Setup tmate Session
      uses: mxschmitt/action-tmate@v3  # Updated to v3 for stability [[7]]
