name: macOS-VNC-Playit
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pinggy tunnel URL
        run: |
          # Pinggy outputs the public URL directly to stdout
          echo "Connect via: $(pinggy tcp 5900 | grep -o 'https://.*')"
